# Generated by Django 2.1.4 on 2018-12-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('broken', models.BooleanField()),
                ('Tscore', models.FloatField()),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
